In [71]:
!pip install numpy

You should consider upgrading via the 'C:\Users\lenovo\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [72]:
import numpy as np

In [73]:
l1 = [5, 3, 71, 6]


In [74]:
arr1 = np.array(l1)

In [75]:
l2 = [5, 54.4, 74.2, 2,36]
np.array(l2)

array([ 5. , 54.4, 74.2,  2. , 36. ])

In [76]:
type(arr1)

numpy.ndarray

In [77]:
np.arange(10.5, 20.5, 1.5)

array([10.5, 12. , 13.5, 15. , 16.5, 18. , 19.5])

In [78]:
np.arange(10.5, 20.5, 1.5, dtype='int')

array([10, 12, 14, 16, 18, 20, 22])

In [79]:
arr1.size

4

In [80]:
arr1.shape

(4,)

In [81]:
arr1.ndim

1

In [82]:
arr1.dtype

dtype('int32')

2D Array

In [96]:
arr2 = np.arange(1,10).reshape( (3,3) )

In [84]:
arr2.size

9

In [85]:
arr2.shape

(3, 3)

In [86]:
arr2.ndim

2

In [87]:
arr2.dtype

dtype('int32')

In [88]:
np.zeros( (4,5),dtype ='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [89]:
np.ones( (4,5),dtype ='complex')

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [90]:
np.linspace(10,25,20).reshape(4,5)

array([[10.        , 10.78947368, 11.57894737, 12.36842105, 13.15789474],
       [13.94736842, 14.73684211, 15.52631579, 16.31578947, 17.10526316],
       [17.89473684, 18.68421053, 19.47368421, 20.26315789, 21.05263158],
       [21.84210526, 22.63157895, 23.42105263, 24.21052632, 25.        ]])

Numpy Operations

In [91]:
arr2*5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [92]:
arr2 %2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [93]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
 # 1. Convert [ (1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12) ] in a 2d array of 3, 4
arr2 = [(1, 2, 3, 4),(5, 6, 7, 8),(9, 10, 11, 12)]
a = np.array(arr2)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [104]:
# 2. Create a 2D array of 20 elements.
arr2 = np.arange(1, 21).reshape( (4, 5) )
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [115]:
# 3. Create an array from 10, 50 with a step of 5 and convert to 3 possible array shape combinations.
np.arange(10, 50).reshape(5, 4, 2)

array([[[10, 11],
        [12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23],
        [24, 25]],

       [[26, 27],
        [28, 29],
        [30, 31],
        [32, 33]],

       [[34, 35],
        [36, 37],
        [38, 39],
        [40, 41]],

       [[42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [116]:
np.arange(10, 50).reshape(5, 2, 4)

array([[[10, 11, 12, 13],
        [14, 15, 16, 17]],

       [[18, 19, 20, 21],
        [22, 23, 24, 25]],

       [[26, 27, 28, 29],
        [30, 31, 32, 33]],

       [[34, 35, 36, 37],
        [38, 39, 40, 41]],

       [[42, 43, 44, 45],
        [46, 47, 48, 49]]])

In [117]:
np.arange(10, 50).reshape(2, 5, 4)

array([[[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23, 24, 25],
        [26, 27, 28, 29]],

       [[30, 31, 32, 33],
        [34, 35, 36, 37],
        [38, 39, 40, 41],
        [42, 43, 44, 45],
        [46, 47, 48, 49]]])

In [124]:
mat3 = np.arange(5,50,5).reshape((3,3))

In [160]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [165]:
bool_arr = mat3 % 10 == 0

In [163]:
mat3 [bool_arr]

array([10, 20, 30, 40])

In [128]:
mat3*2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [129]:
mat4 = np.arange(1,10).reshape((3,3))

In [166]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
mat3 + mat4

array([[ 6, 12, 18],
       [24, 30, 36],
       [42, 48, 54]])

In [131]:
#matrix multiplication
mat3 @ mat4

array([[150, 180, 210],
       [330, 405, 480],
       [510, 630, 750]])

In [133]:
mat3.mean()

25.0

In [167]:
mat3.max()

45

In [169]:
mat3.min()

5

In [170]:
mat3.sum()

225

In [135]:
np.random.randint(45, 65,(4,4))

array([[61, 63, 53, 60],
       [50, 50, 49, 54],
       [47, 59, 47, 56],
       [52, 61, 56, 58]])

In [171]:
import random

In [175]:
random.randint(1,6)

3

In [177]:
random.random()

0.14932046921595266

In [180]:
random.choice([ 'gta', 'resident evil 4', 'wot', 'super mario' ])

'wot'

In [185]:
random.choices([ 'gta', 'resident evil 4', 'wot', 'super mario' ], k = 3)

['super mario', 'gta', 'wot']

In [174]:
ultimatrix = np.arange(25).reshape( (5,5) )

In [186]:
ultimatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [144]:
ultimatrix[1]

array([5, 6, 7, 8, 9])

In [190]:
ultimatrix[1][3]

8

In [188]:
ultimatrix[1,1]

6

In [191]:
ultimatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [146]:
ultimatrix[2:5,2]

array([12, 17, 22])

In [147]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [148]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [149]:
np.vstack((mat3,mat4))

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [150]:
np.hstack((mat3,mat4))

array([[ 5, 10, 15,  1,  2,  3],
       [20, 25, 30,  4,  5,  6],
       [35, 40, 45,  7,  8,  9]])

In [192]:
mat5 = np.arange(1,7).reshape((2,3))

In [193]:
mat5

array([[1, 2, 3],
       [4, 5, 6]])

In [194]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [195]:
np.vstack((mat4,mat5))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [197]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [198]:
mat5

array([[1, 2, 3],
       [4, 5, 6]])

In [201]:
np.hstack((mat4,mat3))

array([[ 1,  2,  3,  5, 10, 15],
       [ 4,  5,  6, 20, 25, 30],
       [ 7,  8,  9, 35, 40, 45]])

In [202]:
mat6 = np.arange(1,7).reshape(3,2)

In [203]:
mat6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [205]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [204]:
np.hstack((mat3,mat6))

array([[ 5, 10, 15,  1,  2],
       [20, 25, 30,  3,  4],
       [35, 40, 45,  5,  6]])